language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_install:
  - composer self-update

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install -n
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script: phpunit --stop-on-failure

notifications:
   email: a.fiori@cheapnet.it
