homepage:
    pattern:  /
    defaults: { _controller: AcmeReqBundle:Default:index }

acme_quiz:
    pattern:  /quiz/
    defaults: { _controller: AcmeReqBundle:Quiz:index }
    requirements:
        _method: GET

acme_quiz_topic:
    pattern:  /quiz/topic/{topic}
    defaults: { _controller: AcmeReqBundle:Quiz:index }
    requirements:
        topic: "[a-zA-Z0-9-_/]+"
        _method:  GET

acme_quiz_tags:
    pattern:  /quiz/tags/{tag}
    defaults: { _controller: AcmeReqBundle:Quiz:index }
    requirements:
        topic: "[a-zA-Z0-9-_/]+"
        _method: GET
       
acme_quiz_topic_tags:
    pattern:  /quiz/topic/{topic}/{tag}
    defaults: { _controller: AcmeReqBundle:Quiz:index }
    requirements:
        topic: "[a-zA-Z0-9-_/]+"
        _method: GET

acme_interview:
    pattern: /interview/
    defaults:
        _controller: AcmeReqBundle:Interview:index
        permanent: true
    requirements:
            _method: GET

acme_interview_topic:
    pattern:  /interview/topic/{topic}
    defaults: { _controller: AcmeReqBundle:Interview:list }
    requirements:
        topic: "[a-zA-Z0-9-_/]+"
        _method: GET

acme_interview_tags:
    pattern:  /interview/tags/{tag}
    defaults: { _controller: AcmeReqBundle:Interview:list }
    requirements:
        tag: "[a-zA-Z0-9-_/]+"
        _method: GET

acme_api:
    pattern: /api/
    defaults:
        _controller: AcmeReqBundle:Api:index
        permanent: true
