parameters:
#    acme_quiz.example.class: Acme\ReqBundle\Example

services:
#    acme_quiz.example:
#        class: %acme_quiz.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
